#!/bin/bash

# This creates an inline JCL file to install RAKFCL to SYS2.EXEC

username="HERC01"
password="CUL8TR"
linklib="SYS2.LINKLIB"

cat << END
//AUTOMVS JOB (TSO),
//             'Install AUTOMVS',
//             CLASS=A,
//             MSGCLASS=H,
//             MSGLEVEL=(1,1),
//             USER=$username,PASSWORD=$password
//*
//* THIS JCL AUTOMATICALLY GENERATED BY UPLOAD.sh
//*
//PDSLOAD  EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=$linklib,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYS2.EXEC,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=AUTOMVS
END
cat AUTOMVS.rexx

echo "@@"
echo "/*"
cat << END
//PDSLOAD  EXEC PGM=PDSLOAD
//STEPLIB  DD  DSN=$linklib,DISP=SHR
//SYSPRINT DD  SYSOUT=*
//SYSUT2   DD  DSN=SYS2.PROCLIB,DISP=SHR
//SYSUT1   DD  DATA,DLM=@@
./ ADD NAME=AUTOMVS
END
cat AUTOMVS.jcl

echo "@@"
echo "/*"